on:
  push:
    branches:
      - main
jobs:
  zip:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.6.0
    - uses: vimtor/action-zip@v1
      with:
        files: src
        dest: yuji.zip
    - name: Upload & release
      uses: mnao305/chrome-extension-upload@v4.0.0
      with:
        file-path: ./yuji.zip
        extension-id: kdebcnhdaacligojjamibfjjklmabjli
        client-id: ${{ secrets.CLIENT_ID }}
        client-secret: ${{ secrets.CLIENT_SECRET }}
        refresh-token: ${{ secrets.REFRESH_TOKEN }}